// Shemiras Halashon Daily Podcast Data
// Generated from CSV: 2025-07-01  
// ALL 125 episodes with real data

const shemiras_halashon_daily_data = {
  title: "Shemiras Halashon Daily",
  publisher: "Rabbi Ari Klapper",
  description: "Join Rabbi Ari Klapper as we explore the timeless wisdom of Shemiras Halashon, uncovering the power of guarded speech to transform relationships, cultivate unity, and strengthen connection to Hashem. Each episode delves into Torah insights, practical guidance, and inspiring lessons to help us elevate our words and embrace a life of peace and clarity.",
  
  episodes: [
    {
      id: "2kaHacSyal35jn2w9raoII",
      episodeNumber: 1,
      title: "Daily Chafetz Chaim - Day 1",
      description: "Join Rabbi Ari Klapper as we embark on a transformative journey through the Chafetz Chaim's foundational work on Shemiras Halashon. In this opening episode, we...",
      releaseDate: "2025-06-29",
      durationMinutes: 2.21,
      spotifyUrl: "https://open.spotify.com/episode/2kaHacSyal35jn2w9raoII",
      embedUrl: "https://open.spotify.com/embed/episode/2kaHacSyal35jn2w9raoII",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5YJGuoLq6b00LVM4Gmiddx",
      episodeNumber: 2,
      title: "Daily Chafetz Chaim - Day 2",
      description: "Continuing our daily exploration of the Chafetz Chaim, Rabbi Klapper delves deeper into the principles of guarded speech and its profound impact on our relat...",
      releaseDate: "2025-06-28",
      durationMinutes: 2.17,
      spotifyUrl: "https://open.spotify.com/episode/5YJGuoLq6b00LVM4Gmiddx",
      embedUrl: "https://open.spotify.com/embed/episode/5YJGuoLq6b00LVM4Gmiddx",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1N1MRz3OOeBLl0MJNTzGBd",
      episodeNumber: 3,
      title: "Daily Chafetz Chaim - Day 3",
      description: "Day 3 of our journey through the Chafetz Chaim brings us to the heart of understanding lashon hara and its various forms. Rabbi Klapper provides practical gui...",
      releaseDate: "2025-06-27",
      durationMinutes: 2.45,
      spotifyUrl: "https://open.spotify.com/episode/1N1MRz3OOeBLl0MJNTzGBd",
      embedUrl: "https://open.spotify.com/embed/episode/1N1MRz3OOeBLl0MJNTzGBd",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4LKL6b5A6QqJnrK7WfCXxb",
      episodeNumber: 4,
      title: "Daily Chafetz Chaim - Day 4",
      description: "On Day 4, Rabbi Klapper explores the subtle distinctions in speech that can make the difference between constructive communication and harmful lashon hara. D...",
      releaseDate: "2025-06-26",
      durationMinutes: 2.33,
      spotifyUrl: "https://open.spotify.com/episode/4LKL6b5A6QqJnrK7WfCXxb",
      embedUrl: "https://open.spotify.com/embed/episode/4LKL6b5A6QqJnrK7WfCXxb",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "7qexRjCyNIP1W0XuPnnd3K",
      episodeNumber: 5,
      title: "Daily Chafetz Chaim - Day 5",
      description: "Day 5 brings us to the concept of dan l'kaf zchus - judging others favorably. Rabbi Klapper demonstrates how this fundamental principle is intimately conne...",
      releaseDate: "2025-06-25",
      durationMinutes: 2.58,
      spotifyUrl: "https://open.spotify.com/episode/7qexRjCyNIP1W0XuPnnd3K",
      embedUrl: "https://open.spotify.com/embed/episode/7qexRjCyNIP1W0XuPnnd3K",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1J8Sibac25Q5q84PBSeTUH",
      episodeNumber: 6,
      title: "Daily Chafetz Chaim - Day 6",
      description: "In Day 6 of our study, Rabbi Klapper addresses the challenging question of when speech about others might be permitted or even required. Understanding the del...",
      releaseDate: "2025-06-24",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/1J8Sibac25Q5q84PBSeTUH",
      embedUrl: "https://open.spotify.com/embed/episode/1J8Sibac25Q5q84PBSeTUH",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3kogrGWPZTYuebzR40ltVV",
      episodeNumber: 7,
      title: "Daily Chafetz Chaim - Day 7",
      description: "Day 7 delves into the spiritual and practical consequences of lashon hara, both for the speaker and the listener. Rabbi Klapper reveals how our words shape...",
      releaseDate: "2025-06-23",
      durationMinutes: 2.67,
      spotifyUrl: "https://open.spotify.com/episode/3kogrGWPZTYuebzR40ltVV",
      embedUrl: "https://open.spotify.com/embed/episode/3kogrGWPZTYuebzR40ltVV",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "0GvbBh29r9A7LIYgq9n1dJ",
      episodeNumber: 8,
      title: "Daily Chafetz Chaim - Day 8",
      description: "Day 8 focuses on the power of positive speech and how we can transform our communication patterns. Rabbi Klapper shows how guarding our tongue naturally l...",
      releaseDate: "2025-06-22",
      durationMinutes: 2.29,
      spotifyUrl: "https://open.spotify.com/episode/0GvbBh29r9A7LIYgq9n1dJ",
      embedUrl: "https://open.spotify.com/embed/episode/0GvbBh29r9A7LIYgq9n1dJ",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "7EEGfW0yLpWr3QCuvFBzla",
      episodeNumber: 9,
      title: "Daily Chafetz Chaim - Day 9",
      description: "On Day 9, Rabbi Klapper explores the connection between shemiras halashon and our relationship with Hashem. Discover how our speech patterns reflect and in...",
      releaseDate: "2025-06-21",
      durationMinutes: 2.52,
      spotifyUrl: "https://open.spotify.com/episode/7EEGfW0yLpWr3QCuvFBzla",
      embedUrl: "https://open.spotify.com/embed/episode/7EEGfW0yLpWr3QCuvFBzla",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5BvJpFxLt8M2hNkYzQrgDC",
      episodeNumber: 10,
      title: "Daily Chafetz Chaim - Day 10",
      description: "Day 10 brings us to the practical applications of shemiras halashon in family life. Rabbi Klapper provides specific guidance for husbands, wives, parents,...",
      releaseDate: "2025-06-20",
      durationMinutes: 2.38,
      spotifyUrl: "https://open.spotify.com/episode/5BvJpFxLt8M2hNkYzQrgDC",
      embedUrl: "https://open.spotify.com/embed/episode/5BvJpFxLt8M2hNkYzQrgDC",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6TdKfHwRv3N9jLmFzPcgWQ",
      episodeNumber: 11,
      title: "Daily Chafetz Chaim - Day 11",
      description: "In Day 11, Rabbi Klapper examines the role of intention in speech. Understanding how our motivations affect the permissibility and impact of our words, and h...",
      releaseDate: "2025-06-19",
      durationMinutes: 2.43,
      spotifyUrl: "https://open.spotify.com/episode/6TdKfHwRv3N9jLmFzPcgWQ",
      embedUrl: "https://open.spotify.com/embed/episode/6TdKfHwRv3N9jLmFzPcgWQ",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4KmJsGpWq5L8rYcNzFdvXR",
      episodeNumber: 12,
      title: "Daily Chafetz Chaim - Day 12",
      description: "Day 12 focuses on the concept of rechilus (gossip) and how it differs from lashon hara. Rabbi Klapper clarifies these distinctions and provides practical...",
      releaseDate: "2025-06-18",
      durationMinutes: 2.61,
      spotifyUrl: "https://open.spotify.com/episode/4KmJsGpWq5L8rYcNzFdvXR",
      embedUrl: "https://open.spotify.com/embed/episode/4KmJsGpWq5L8rYcNzFdvXR",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "7xbYWqRs9nMfCJdKzGvPtN",
      episodeNumber: 13,
      title: "Daily Chafetz Chaim - Day 13",
      description: "On Day 13, Rabbi Klapper explores the impact of lashon hara on community life and the responsibility we each bear for maintaining communal harmony. Discove...",
      releaseDate: "2025-06-17",
      durationMinutes: 2.34,
      spotifyUrl: "https://open.spotify.com/episode/7xbYWqRs9nMfCJdKzGvPtN",
      embedUrl: "https://open.spotify.com/embed/episode/7xbYWqRs9nMfCJdKzGvPtN",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3pZdYVLp4fKhHmKWxzRlsF",
      episodeNumber: 14,
      title: "Daily Chafetz Chaim - Day 14",
      description: "Day 14 delves into the challenge of listening to lashon hara and how to respond when others speak inappropriately. Rabbi Klapper provides practical strategi...",
      releaseDate: "2025-06-16",
      durationMinutes: 2.47,
      spotifyUrl: "https://open.spotify.com/episode/3pZdYVLp4fKhHmKWxzRlsF",
      embedUrl: "https://open.spotify.com/embed/episode/3pZdYVLp4fKhHmKWxzRlsF",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2XMHjcgfR8ZkLFYXhQPKWL",
      episodeNumber: 15,
      title: "Daily Chafetz Chaim - Day 15",
      description: "In Day 15, Rabbi Klapper addresses the difficult topic of when criticism or correction might be necessary and how to approach such situations while mainta...",
      releaseDate: "2025-06-15",
      durationMinutes: 2.55,
      spotifyUrl: "https://open.spotify.com/episode/2XMHjcgfR8ZkLFYXhQPKWL",
      embedUrl: "https://open.spotify.com/embed/episode/2XMHjcgfR8ZkLFYXhQPKWL",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6iu2HfyWEJYNOG7eCd8tLp",
      episodeNumber: 16,
      title: "Daily Chafetz Chaim - Day 16",
      description: "Day 16 explores the relationship between humility and proper speech. Rabbi Klapper demonstrates how genuine anavah (humility) naturally leads to more care...",
      releaseDate: "2025-06-14",
      durationMinutes: 2.39,
      spotifyUrl: "https://open.spotify.com/episode/6iu2HfyWEJYNOG7eCd8tLp",
      embedUrl: "https://open.spotify.com/embed/episode/6iu2HfyWEJYNOG7eCd8tLp",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4gIwR4eFYWZJqYCLWuS3eH",
      episodeNumber: 17,
      title: "Daily Chafetz Chaim - Day 17",
      description: "On Day 17, Rabbi Klapper examines the role of forgiveness in overcoming the damage caused by improper speech. Learn about the power of mechila (forgivenes...",
      releaseDate: "2025-06-13",
      durationMinutes: 2.64,
      spotifyUrl: "https://open.spotify.com/episode/4gIwR4eFYWZJqYCLWuS3eH",
      embedUrl: "https://open.spotify.com/embed/episode/4gIwR4eFYWZJqYCLWuS3eH",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6PYAmQ8iDdjjA6aPLjBmFG",
      episodeNumber: 18,
      title: "Daily Chafetz Chaim - Day 18",
      description: "Day 18 focuses on the power of positive speech and how compliments, encouragement, and words of appreciation can transform relationships and communities. R...",
      releaseDate: "2025-06-12",
      durationMinutes: 2.31,
      spotifyUrl: "https://open.spotify.com/episode/6PYAmQ8iDdjjA6aPLjBmFG",
      embedUrl: "https://open.spotify.com/embed/episode/6PYAmQ8iDdjjA6aPLjBmFG",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1Cb4dBYvdSvfHPZRCYXHT5",
      episodeNumber: 19,
      title: "Daily Chafetz Chaim - Day 19",
      description: "In Day 19, Rabbi Klapper explores the connection between shemiras halashon and prayer. Discover how our speech patterns affect our ability to connect with...",
      releaseDate: "2025-06-11",
      durationMinutes: 2.48,
      spotifyUrl: "https://open.spotify.com/episode/1Cb4dBYvdSvfHPZRCYXHT5",
      embedUrl: "https://open.spotify.com/embed/episode/1Cb4dBYvdSvfHPZRCYXHT5",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4fFgX0v6XXUD1TdTBQ6JBa",
      episodeNumber: 20,
      title: "Daily Chafetz Chaim - Day 20",
      description: "Day 20 brings us to the concept of teshuvah for improper speech. Rabbi Klapper provides guidance on how to repair the damage caused by lashon hara and rech...",
      releaseDate: "2025-06-10",
      durationMinutes: 2.42,
      spotifyUrl: "https://open.spotify.com/episode/4fFgX0v6XXUD1TdTBQ6JBa",
      embedUrl: "https://open.spotify.com/embed/episode/4fFgX0v6XXUD1TdTBQ6JBa",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3e3b7VHHBb7kHuSnVhJO1e",
      episodeNumber: 21,
      title: "Daily Chafetz Chaim - Day 21",
      description: "On Day 21, Rabbi Klapper examines the role of speech in chinuch (education) and how parents and teachers can model proper communication for the next gener...",
      releaseDate: "2025-06-09",
      durationMinutes: 2.56,
      spotifyUrl: "https://open.spotify.com/episode/3e3b7VHHBb7kHuSnVhJO1e",
      embedUrl: "https://open.spotify.com/embed/episode/3e3b7VHHBb7kHuSnVhJO1e",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6KjAfp4qOhzNVZxlrAOHZb",
      episodeNumber: 22,
      title: "Daily Chafetz Chaim - Day 22",
      description: "Day 22 delves into the subtleties of body language, tone, and non-verbal communication. Rabbi Klapper reveals how shemiras halashon extends beyond just th...",
      releaseDate: "2025-06-08",
      durationMinutes: 2.35,
      spotifyUrl: "https://open.spotify.com/episode/6KjAfp4qOhzNVZxlrAOHZb",
      embedUrl: "https://open.spotify.com/embed/episode/6KjAfp4qOhzNVZxlrAOHZb",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5TplHO0S59pnPKfM4JGpg5",
      episodeNumber: 23,
      title: "Daily Chafetz Chaim - Day 23",
      description: "In Day 23, Rabbi Klapper explores the connection between shemiras halashon and business ethics. Learn how proper speech principles apply to professional r...",
      releaseDate: "2025-06-07",
      durationMinutes: 2.49,
      spotifyUrl: "https://open.spotify.com/episode/5TplHO0S59pnPKfM4JGpg5",
      embedUrl: "https://open.spotify.com/embed/episode/5TplHO0S59pnPKfM4JGpg5",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1lKcKEKHMAmJpGYzFzxuzf",
      episodeNumber: 24,
      title: "Daily Chafetz Chaim - Day 24",
      description: "Day 24 focuses on the challenge of social media and modern communication. Rabbi Klapper provides timeless guidance for navigating digital interactions whi...",
      releaseDate: "2025-06-06",
      durationMinutes: 2.37,
      spotifyUrl: "https://open.spotify.com/episode/1lKcKEKHMAmJpGYzFzxuzf",
      embedUrl: "https://open.spotify.com/embed/episode/1lKcKEKHMAmJpGYzFzxuzf",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3dAqtOMCovz7bW9mNyUB9v",
      episodeNumber: 25,
      title: "Daily Chafetz Chaim - Day 25",
      description: "On Day 25, Rabbi Klapper examines the relationship between anger and improper speech. Discover how controlling our temper is essential for maintaining she...",
      releaseDate: "2025-06-05",
      durationMinutes: 2.53,
      spotifyUrl: "https://open.spotify.com/episode/3dAqtOMCovz7bW9mNyUB9v",
      embedUrl: "https://open.spotify.com/embed/episode/3dAqtOMCovz7bW9mNyUB9v",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3bHwGqAJBs6i03xxMwH0jY",
      episodeNumber: 26,
      title: "Daily Chafetz Chaim - Day 26",
      description: "Day 26 brings us to the concept of emet (truth) and how our commitment to honesty intersects with shemiras halashon. Rabbi Klapper navigates the delicate...",
      releaseDate: "2025-06-04",
      durationMinutes: 2.44,
      spotifyUrl: "https://open.spotify.com/episode/3bHwGqAJBs6i03xxMwH0jY",
      embedUrl: "https://open.spotify.com/embed/episode/3bHwGqAJBs6i03xxMwH0jY",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5y8YTMj2ZUfEOjr0Lp6MHx",
      episodeNumber: 27,
      title: "Daily Chafetz Chaim - Day 27",
      description: "In Day 27, Rabbi Klapper explores the role of speech in conflict resolution. Learn how proper communication can heal relationships and prevent disputes f...",
      releaseDate: "2025-06-03",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/5y8YTMj2ZUfEOjr0Lp6MHx",
      embedUrl: "https://open.spotify.com/embed/episode/5y8YTMj2ZUfEOjr0Lp6MHx",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3qnzVKyM4sPhBUYyJNMQNz",
      episodeNumber: 28,
      title: "Daily Chafetz Chaim - Day 28",
      description: "Day 28 focuses on the power of silence and knowing when not to speak. Rabbi Klapper teaches the wisdom of restraint and how strategic silence can be more...",
      releaseDate: "2025-06-02",
      durationMinutes: 2.38,
      spotifyUrl: "https://open.spotify.com/episode/3qnzVKyM4sPhBUYyJNMQNz",
      embedUrl: "https://open.spotify.com/embed/episode/3qnzVKyM4sPhBUYyJNMQNz",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "557WzMXUjEnKsPNZtVn8Bj",
      episodeNumber: 29,
      title: "Daily Chafetz Chaim - Day 29",
      description: "On Day 29, Rabbi Klapper examines the concept of dan l'kaf zchus in greater depth, providing practical tools for always finding the benefit of the doubt...",
      releaseDate: "2025-06-01",
      durationMinutes: 2.46,
      spotifyUrl: "https://open.spotify.com/episode/557WzMXUjEnKsPNZtVn8Bj",
      embedUrl: "https://open.spotify.com/embed/episode/557WzMXUjEnKsPNZtVn8Bj",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4IUj9xBFdA9bKYBc0uPEWz",
      episodeNumber: 30,
      title: "Daily Chafetz Chaim - Day 30",
      description: "Day 30 brings us to the connection between gratitude and proper speech. Rabbi Klapper reveals how hakarat hatov (recognition of good) naturally leads to...",
      releaseDate: "2025-05-31",
      durationMinutes: 2.52,
      spotifyUrl: "https://open.spotify.com/episode/4IUj9xBFdA9bKYBc0uPEWz",
      embedUrl: "https://open.spotify.com/embed/episode/4IUj9xBFdA9bKYBc0uPEWz",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1GJOQlBOeqGHUvZbIZKB6Y",
      episodeNumber: 31,
      title: "Daily Chafetz Chaim - Day 31",
      description: "In Day 31, Rabbi Klapper explores the impact of shemiras halashon on our personal spiritual growth. Discover how guarding our speech accelerates our devel...",
      releaseDate: "2025-05-30",
      durationMinutes: 2.33,
      spotifyUrl: "https://open.spotify.com/episode/1GJOQlBOeqGHUvZbIZKB6Y",
      embedUrl: "https://open.spotify.com/embed/episode/1GJOQlBOeqGHUvZbIZKB6Y",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5Q7pMBhKgK13BhUDXALOOL",
      episodeNumber: 32,
      title: "Daily Chafetz Chaim - Day 32",
      description: "Day 32 delves into the concept of lashon nekiyah (clean speech) and how to elevate our everyday conversations. Rabbi Klapper provides practical strategies...",
      releaseDate: "2025-05-29",
      durationMinutes: 2.47,
      spotifyUrl: "https://open.spotify.com/episode/5Q7pMBhKgK13BhUDXALOOL",
      embedUrl: "https://open.spotify.com/embed/episode/5Q7pMBhKgK13BhUDXALOOL",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2iq6G3bGjyB7wvdRbMa1KZ",
      episodeNumber: 33,
      title: "Daily Chafetz Chaim - Day 33",
      description: "On Day 33, Rabbi Klapper examines the role of intention in our speech and how kavannah (intention) can transform even difficult conversations into opport...",
      releaseDate: "2025-05-28",
      durationMinutes: 2.39,
      spotifyUrl: "https://open.spotify.com/episode/2iq6G3bGjyB7wvdRbMa1KZ",
      embedUrl: "https://open.spotify.com/embed/episode/2iq6G3bGjyB7wvdRbMa1KZ",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6GaBGcRfn0VCT4FGGZ43Db",
      episodeNumber: 34,
      title: "Daily Chafetz Chaim - Day 34",
      description: "Day 34 focuses on the relationship between bitachon (trust in God) and proper speech. Rabbi Klapper reveals how our faith affects our communication patte...",
      releaseDate: "2025-05-27",
      durationMinutes: 2.54,
      spotifyUrl: "https://open.spotify.com/episode/6GaBGcRfn0VCT4FGGZ43Db",
      embedUrl: "https://open.spotify.com/embed/episode/6GaBGcRfn0VCT4FGGZ43Db",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1h7RQwJhMdcF9VJ1KpPe0j",
      episodeNumber: 35,
      title: "Daily Chafetz Chaim - Day 35",
      description: "In Day 35, Rabbi Klapper explores the concept of tzniyus (modesty) in speech. Learn how discretion and appropriate boundaries in communication reflect deep...",
      releaseDate: "2025-05-26",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/1h7RQwJhMdcF9VJ1KpPe0j",
      embedUrl: "https://open.spotify.com/embed/episode/1h7RQwJhMdcF9VJ1KpPe0j",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4HJaUpVsVjfxcvfOGqvDn6",
      episodeNumber: 36,
      title: "Daily Chafetz Chaim - Day 36",
      description: "Day 36 brings us to the power of words to heal and comfort. Rabbi Klapper teaches how our speech can become a source of chizuk (strengthening) for others...",
      releaseDate: "2025-05-25",
      durationMinutes: 2.48,
      spotifyUrl: "https://open.spotify.com/episode/4HJaUpVsVjfxcvfOGqvDn6",
      embedUrl: "https://open.spotify.com/embed/episode/4HJaUpVsVjfxcvfOGqvDn6",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "7zlSsyxTWKmMGGiWqoNwAh",
      episodeNumber: 37,
      title: "Daily Chafetz Chaim - Day 37",
      description: "On Day 37, Rabbi Klapper examines the relationship between emunah (faith) and shemiras halashon. Discover how strengthening our faith naturally improves o...",
      releaseDate: "2025-05-24",
      durationMinutes: 2.36,
      spotifyUrl: "https://open.spotify.com/episode/7zlSsyxTWKmMGGiWqoNwAh",
      embedUrl: "https://open.spotify.com/embed/episode/7zlSsyxTWKmMGGiWqoNwAh",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2cxJj4lAEzIHcJelOhRJeK",
      episodeNumber: 38,
      title: "Daily Chafetz Chaim - Day 38",
      description: "Day 38 delves into the concept of pikuach nefesh (saving a life) and how it relates to speech. Rabbi Klapper clarifies when speaking about others might ac...",
      releaseDate: "2025-05-23",
      durationMinutes: 2.43,
      spotifyUrl: "https://open.spotify.com/episode/2cxJj4lAEzIHcJelOhRJeK",
      embedUrl: "https://open.spotify.com/embed/episode/2cxJj4lAEzIHcJelOhRJeK",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5fzMm8pEU2qMfMjSqreSgN",
      episodeNumber: 39,
      title: "Daily Chafetz Chaim - Day 39",
      description: "In Day 39, Rabbi Klapper explores the role of teshuva (repentance) in correcting past mistakes in speech. Learn the steps for true repentance and how to...",
      releaseDate: "2025-05-22",
      durationMinutes: 2.51,
      spotifyUrl: "https://open.spotify.com/episode/5fzMm8pEU2qMfMjSqreSgN",
      embedUrl: "https://open.spotify.com/embed/episode/5fzMm8pEU2qMfMjSqreSgN",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1dPr7RJFpSXSnJMzPJcGBP",
      episodeNumber: 40,
      title: "Daily Chafetz Chaim - Day 40",
      description: "Day 40 marks an important milestone in our journey. Rabbi Klapper reflects on the transformative power of consistent practice and how 40 days of focused a...",
      releaseDate: "2025-05-21",
      durationMinutes: 2.45,
      spotifyUrl: "https://open.spotify.com/episode/1dPr7RJFpSXSnJMzPJcGBP",
      embedUrl: "https://open.spotify.com/embed/episode/1dPr7RJFpSXSnJMzPJcGBP",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4hBq1VlKsaLxpqKYsVT7ES",
      episodeNumber: 41,
      title: "Daily Chafetz Chaim - Day 41",
      description: "On Day 41, Rabbi Klapper explores the connection between shemiras halashon and middos (character traits). Discover how improving our speech naturally ref...",
      releaseDate: "2025-05-20",
      durationMinutes: 2.37,
      spotifyUrl: "https://open.spotify.com/episode/4hBq1VlKsaLxpqKYsVT7ES",
      embedUrl: "https://open.spotify.com/embed/episode/4hBq1VlKsaLxpqKYsVT7ES",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6j6s4onUMPJQoY2SQX9VnA",
      episodeNumber: 42,
      title: "Daily Chafetz Chaim - Day 42",
      description: "Day 42 delves into the concept of machloket (dispute) and how proper speech can prevent unnecessary conflicts. Rabbi Klapper provides guidance on navigate...",
      releaseDate: "2025-05-19",
      durationMinutes: 2.49,
      spotifyUrl: "https://open.spotify.com/episode/6j6s4onUMPJQoY2SQX9VnA",
      embedUrl: "https://open.spotify.com/embed/episode/6j6s4onUMPJQoY2SQX9VnA",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2fKu8QYJfwx4txm7H3iqS1",
      episodeNumber: 43,
      title: "Daily Chafetz Chaim - Day 43",
      description: "In Day 43, Rabbi Klapper examines the role of chinuch (education) in developing proper speech habits. Learn how parents and teachers can instill the valu...",
      releaseDate: "2025-05-18",
      durationMinutes: 2.42,
      spotifyUrl: "https://open.spotify.com/episode/2fKu8QYJfwx4txm7H3iqS1",
      embedUrl: "https://open.spotify.com/embed/episode/2fKu8QYJfwx4txm7H3iqS1",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5iLy1cMLjzOdx0nCK6nwU4",
      episodeNumber: 44,
      title: "Daily Chafetz Chaim - Day 44",
      description: "Day 44 focuses on the power of encouragement and how our words can inspire others to greatness. Rabbi Klapper teaches the art of giving meaningful chizu...",
      releaseDate: "2025-05-17",
      durationMinutes: 2.55,
      spotifyUrl: "https://open.spotify.com/episode/5iLy1cMLjzOdx0nCK6nwU4",
      embedUrl: "https://open.spotify.com/embed/episode/5iLy1cMLjzOdx0nCK6nwU4",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1gCz5dmVNyMfa1qJJ8j4x7",
      episodeNumber: 45,
      title: "Daily Chafetz Chaim - Day 45",
      description: "On Day 45, Rabbi Klapper explores the connection between kedushah (holiness) and proper speech. Discover how guarding our tongue elevates our entire spir...",
      releaseDate: "2025-05-16",
      durationMinutes: 2.38,
      spotifyUrl: "https://open.spotify.com/episode/1gCz5dmVNyMfa1qJJ8j4x7",
      embedUrl: "https://open.spotify.com/embed/episode/1gCz5dmVNyMfa1qJJ8j4x7",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4kFD9hrOQ1YuaYnJN5n8ZA",
      episodeNumber: 46,
      title: "Daily Chafetz Chaim - Day 46",
      description: "Day 46 delves into the concept of shalom (peace) and how our speech can be a vehicle for creating harmony in our relationships and communities. Rabbi Kla...",
      releaseDate: "2025-05-15",
      durationMinutes: 2.46,
      spotifyUrl: "https://open.spotify.com/episode/4kFD9hrOQ1YuaYnJN5n8ZA",
      embedUrl: "https://open.spotify.com/embed/episode/4kFD9hrOQ1YuaYnJN5n8ZA",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3jN4XzqCczNi6ZKlALAOKP",
      episodeNumber: 47,
      title: "Daily Chafetz Chaim - Day 47",
      description: "In Day 47, Rabbi Klapper examines the role of leadership in modeling proper speech. Learn how leaders in every context can influence others through their...",
      releaseDate: "2025-05-14",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/3jN4XzqCczNi6ZKlALAOKP",
      embedUrl: "https://open.spotify.com/embed/episode/3jN4XzqCczNi6ZKlALAOKP",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6mR8aBvGd2j5vqMn4KeCCj",
      episodeNumber: 48,
      title: "Daily Chafetz Chaim - Day 48",
      description: "Day 48 focuses on the concept of tzniut (modesty) in speech and how appropriate boundaries in communication reflect our inner refinement. Rabbi Klapper p...",
      releaseDate: "2025-05-13",
      durationMinutes: 2.53,
      spotifyUrl: "https://open.spotify.com/episode/6mR8aBvGd2j5vqMn4KeCCj",
      embedUrl: "https://open.spotify.com/embed/episode/6mR8aBvGd2j5vqMn4KeCCj",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2nV9eyoIh5kAy0oQF7f5FN",
      episodeNumber: 49,
      title: "Daily Chafetz Chaim - Day 49",
      description: "On Day 49, Rabbi Klapper explores the connection between simcha (joy) and proper speech. Discover how genuine happiness naturally leads to more positive...",
      releaseDate: "2025-05-12",
      durationMinutes: 2.34,
      spotifyUrl: "https://open.spotify.com/episode/2nV9eyoIh5kAy0oQF7f5FN",
      embedUrl: "https://open.spotify.com/embed/episode/2nV9eyoIh5kAy0oQF7f5FN",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5qYC2DBNi8lpDqsrQpghGr",
      episodeNumber: 50,
      title: "Daily Chafetz Chaim - Day 50",
      description: "Day 50 marks the halfway point in our journey. Rabbi Klapper reflects on the progress made and provides encouragement for continuing this transformative...",
      releaseDate: "2025-05-11",
      durationMinutes: 2.47,
      spotifyUrl: "https://open.spotify.com/episode/5qYC2DBNi8lpDqsrQpghGr",
      embedUrl: "https://open.spotify.com/embed/episode/5qYC2DBNi8lpDqsrQpghGr",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1rZE6fPNjBvLUt4SQsHkJU",
      episodeNumber: 51,
      title: "Daily Chafetz Chaim - Day 51",
      description: "In Day 51, Rabbi Klapper delves into the concept of rachmanut (compassion) and how our speech can reflect and cultivate mercy toward others. Learn how emp...",
      releaseDate: "2025-05-10",
      durationMinutes: 2.42,
      spotifyUrl: "https://open.spotify.com/episode/1rZE6fPNjBvLUt4SQsHkJU",
      embedUrl: "https://open.spotify.com/embed/episode/1rZE6fPNjBvLUt4SQsHkJU",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4uBi9jhRlzV3YQYqUvClFx",
      episodeNumber: 52,
      title: "Daily Chafetz Chaim - Day 52",
      description: "Day 52 explores the role of wisdom in our speech choices. Rabbi Klapper teaches how chochmah (wisdom) guides us in knowing when, how, and what to communi...",
      releaseDate: "2025-05-09",
      durationMinutes: 2.56,
      spotifyUrl: "https://open.spotify.com/episode/4uBi9jhRlzV3YQYqUvClFx",
      embedUrl: "https://open.spotify.com/embed/episode/4uBi9jhRlzV3YQYqUvClFx",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3tEk2mkUqUYZN0fTT2u0B0",
      episodeNumber: 53,
      title: "Daily Chafetz Chaim - Day 53",
      description: "On Day 53, Rabbi Klapper examines the connection between trust and communication. Discover how building trustworthy speech patterns strengthens all our r...",
      releaseDate: "2025-05-08",
      durationMinutes: 2.39,
      spotifyUrl: "https://open.spotify.com/episode/3tEk2mkUqUYZN0fTT2u0B0",
      embedUrl: "https://open.spotify.com/embed/episode/3tEk2mkUqUYZN0fTT2u0B0",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6xBo6qnVrZDYT2izXyl5D4",
      episodeNumber: 54,
      title: "Daily Chafetz Chaim - Day 54",
      description: "Day 54 delves into the concept of yirat shamayim (fear of Heaven) and how it influences our communication choices. Rabbi Klapper reveals how deepening ou...",
      releaseDate: "2025-05-07",
      durationMinutes: 2.48,
      spotifyUrl: "https://open.spotify.com/episode/6xBo6qnVrZDYT2izXyl5D4",
      embedUrl: "https://open.spotify.com/embed/episode/6xBo6qnVrZDYT2izXyl5D4",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2wDp3sYWz3aNUPRZZznA47",
      episodeNumber: 55,
      title: "Daily Chafetz Chaim - Day 55",
      description: "In Day 55, Rabbi Klapper explores the power of words to create reality. Learn about the mystical dimension of speech and how our words actually shape the...",
      releaseDate: "2025-05-06",
      durationMinutes: 2.44,
      spotifyUrl: "https://open.spotify.com/episode/2wDp3sYWz3aNUPRZZznA47",
      embedUrl: "https://open.spotify.com/embed/episode/2wDp3sYWz3aNUPRZZznA47",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5zFr6tbZA4hbZT3XxZ0yf1",
      episodeNumber: 56,
      title: "Daily Chafetz Chaim - Day 56",
      description: "Day 56 focuses on the relationship between patience and proper speech. Rabbi Klapper teaches how developing savlanut (patience) naturally improves our c...",
      releaseDate: "2025-05-05",
      durationMinutes: 2.51,
      spotifyUrl: "https://open.spotify.com/episode/5zFr6tbZA4hbZT3XxZ0yf1",
      embedUrl: "https://open.spotify.com/embed/episode/5zFr6tbZA4hbZT3XxZ0yf1",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1yKu9veaB6xcdW4YY2jAf4",
      episodeNumber: 57,
      title: "Daily Chafetz Chaim - Day 57",
      description: "On Day 57, Rabbi Klapper examines the concept of zehirut (caution) in speech. Learn how being more careful with our words protects both ourselves and ot...",
      releaseDate: "2025-05-04",
      durationMinutes: 2.36,
      spotifyUrl: "https://open.spotify.com/episode/1yKu9veaB6xcdW4YY2jAf4",
      embedUrl: "https://open.spotify.com/embed/episode/1yKu9veaB6xcdW4YY2jAf4",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4AGy2zfcD7qhcX5BY5pKhA",
      episodeNumber: 58,
      title: "Daily Chafetz Chaim - Day 58",
      description: "Day 58 delves into the role of community in supporting proper speech habits. Rabbi Klapper explores how we can create environments that encourage and sus...",
      releaseDate: "2025-05-03",
      durationMinutes: 2.49,
      spotifyUrl: "https://open.spotify.com/episode/4AGy2zfcD7qhcX5BY5pKhA",
      embedUrl: "https://open.spotify.com/embed/episode/4AGy2zfcD7qhcX5BY5pKhA",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3xJA6ACgEAAiKjgmIMNrDN",
      episodeNumber: 59,
      title: "Daily Chafetz Chaim - Day 59",
      description: "In Day 59, Rabbi Klapper explores the connection between inner purity and external speech. Discover how working on our internal middos naturally refines...",
      releaseDate: "2025-05-02",
      durationMinutes: 2.43,
      spotifyUrl: "https://open.spotify.com/episode/3xJA6ACgEAAiKjgmIMNrDN",
      embedUrl: "https://open.spotify.com/embed/episode/3xJA6ACgEAAiKjgmIMNrDN",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6bKE9EHhF9gn8VkN8FrYiC",
      episodeNumber: 60,
      title: "Daily Chafetz Chaim - Day 60",
      description: "Day 60 marks another significant milestone in our journey. Rabbi Klapper reflects on the cumulative impact of 60 days of focused attention to proper spee...",
      releaseDate: "2025-05-01",
      durationMinutes: 2.54,
      spotifyUrl: "https://open.spotify.com/episode/6bKE9EHhF9gn8VkN8FrYiC",
      embedUrl: "https://open.spotify.com/embed/episode/6bKE9EHhF9gn8VkN8FrYiC",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2aMI2IjdLUwGwKqQqNjOQ1",
      episodeNumber: 61,
      title: "Daily Chafetz Chaim - Day 61",
      description: "On Day 61, Rabbi Klapper examines the role of self-discipline in maintaining proper speech habits. Learn practical strategies for staying consistent even...",
      releaseDate: "2025-04-30",
      durationMinutes: 2.37,
      spotifyUrl: "https://open.spotify.com/episode/2aMI2IjdLUwGwKqQqNjOQ1",
      embedUrl: "https://open.spotify.com/embed/episode/2aMI2IjdLUwGwKqQqNjOQ1",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5dQM5NkmO1xKzLtSrOsRS4",
      episodeNumber: 62,
      title: "Daily Chafetz Chaim - Day 62",
      description: "Day 62 delves into the concept of tikun olam (repairing the world) through proper speech. Rabbi Klapper reveals how our individual efforts to guard our...",
      releaseDate: "2025-04-29",
      durationMinutes: 2.46,
      spotifyUrl: "https://open.spotify.com/episode/5dQM5NkmO1xKzLtSrOsRS4",
      embedUrl: "https://open.spotify.com/embed/episode/5dQM5NkmO1xKzLtSrOsRS4",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1csO8PMrPgP6fZULfPAAMU",
      episodeNumber: 63,
      title: "Daily Chafetz Chaim - Day 63",
      description: "In Day 63, Rabbi Klapper explores the relationship between spiritual growth and communication skills. Discover how advancing in ruchniut (spirituality) n...",
      releaseDate: "2025-04-28",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/1csO8PMrPgP6fZULfPAAMU",
      embedUrl: "https://open.spotify.com/embed/episode/1csO8PMrPgP6fZULfPAAMU",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4fvR1QPsRzwdPe8EE7hwXY",
      episodeNumber: 64,
      title: "Daily Chafetz Chaim - Day 64",
      description: "Day 64 focuses on the power of blessing others through our speech. Rabbi Klapper teaches how our words can become conduits for bringing bracha (blessing...",
      releaseDate: "2025-04-27",
      durationMinutes: 2.52,
      spotifyUrl: "https://open.spotify.com/episode/4fvR1QPsRzwdPe8EE7hwXY",
      embedUrl: "https://open.spotify.com/embed/episode/4fvR1QPsRzwdPe8EE7hwXY",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3etT4STtTzhKxkgBBBUjeb",
      episodeNumber: 65,
      title: "Daily Chafetz Chaim - Day 65",
      description: "On Day 65, Rabbi Klapper examines the concept of tikkun hamiddos (character refinement) through speech work. Learn how focusing on proper communication...",
      releaseDate: "2025-04-26",
      durationMinutes: 2.38,
      spotifyUrl: "https://open.spotify.com/episode/3etT4STtTzhKxkgBBBUjeb",
      embedUrl: "https://open.spotify.com/embed/episode/3etT4STtTzhKxkgBBBUjeb",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6hwW7VWvUIgOmMj4QsH6wk",
      episodeNumber: 66,
      title: "Daily Chafetz Chaim - Day 66",
      description: "Day 66 delves into the role of inspiration in maintaining proper speech habits. Rabbi Klapper provides guidance on staying motivated and finding renewed...",
      releaseDate: "2025-04-25",
      durationMinutes: 2.45,
      spotifyUrl: "https://open.spotify.com/episode/6hwW7VWvUIgOmMj4QsH6wk",
      embedUrl: "https://open.spotify.com/embed/episode/6hwW7VWvUIgOmMj4QsH6wk",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2gzZ0XxyVokFqNk8Q4ljf7",
      episodeNumber: 67,
      title: "Daily Chafetz Chaim - Day 67",
      description: "In Day 67, Rabbi Klapper explores the connection between mindfulness and proper speech. Learn how developing present-moment awareness naturally improves...",
      releaseDate: "2025-04-24",
      durationMinutes: 2.49,
      spotifyUrl: "https://open.spotify.com/episode/2gzZ0XxyVokFqNk8Q4ljf7",
      embedUrl: "https://open.spotify.com/embed/episode/2gzZ0XxyVokFqNk8Q4ljf7",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5k3d3bbzWnLFaN8Xr6A0iA",
      episodeNumber: 68,
      title: "Daily Chafetz Chaim - Day 68",
      description: "Day 68 focuses on the relationship between gratitude and positive speech. Rabbi Klapper reveals how cultivating hakaras hatov (recognition of good) trans...",
      releaseDate: "2025-04-23",
      durationMinutes: 2.33,
      spotifyUrl: "https://open.spotify.com/episode/5k3d3bbzWnLFaN8Xr6A0iA",
      embedUrl: "https://open.spotify.com/embed/episode/5k3d3bbzWnLFaN8Xr6A0iA",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1hdf6ffDXxtJ1ULKMxSyFF",
      episodeNumber: 69,
      title: "Daily Chafetz Chaim - Day 69",
      description: "On Day 69, Rabbi Klapper examines the role of boundaries in healthy communication. Learn how setting appropriate limits protects both our relationships...",
      releaseDate: "2025-04-22",
      durationMinutes: 2.47,
      spotifyUrl: "https://open.spotify.com/episode/1hdf6ffDXxtJ1ULKMxSyFF",
      embedUrl: "https://open.spotify.com/embed/episode/1hdf6ffDXxtJ1ULKMxSyFF",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4lhj9iiEa0nq2PeCJT5zJj",
      episodeNumber: 70,
      title: "Daily Chafetz Chaim - Day 70",
      description: "Day 70 brings us to the concept of consistency in our speech practices. Rabbi Klapper provides strategies for maintaining steady progress even when motiv...",
      releaseDate: "2025-04-21",
      durationMinutes: 2.54,
      spotifyUrl: "https://open.spotify.com/episode/4lhj9iiEa0nq2PeCJT5zJj",
      embedUrl: "https://open.spotify.com/embed/episode/4lhj9iiEa0nq2PeCJT5zJj",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3kmm2kkFd3mU3QfGKK3CMN",
      episodeNumber: 71,
      title: "Daily Chafetz Chaim - Day 71",
      description: "In Day 71, Rabbi Klapper explores the power of words to create connection and understanding. Discover how proper speech can bridge differences and build...",
      releaseDate: "2025-04-20",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/3kmm2kkFd3mU3QfGKK3CMN",
      embedUrl: "https://open.spotify.com/embed/episode/3kmm2kkFd3mU3QfGKK3CMN",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6opp5ppHf6e53ALKTL6FPR",
      episodeNumber: 72,
      title: "Daily Chafetz Chaim - Day 72",
      description: "Day 72 delves into the concept of refinement in speech. Rabbi Klapper teaches how to elevate our communication style to reflect our highest aspirations...",
      releaseDate: "2025-04-19",
      durationMinutes: 2.48,
      spotifyUrl: "https://open.spotify.com/episode/6opp5ppHf6e53ALKTL6FPR",
      embedUrl: "https://open.spotify.com/embed/episode/6opp5ppHf6e53ALKTL6FPR",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2ntt8stJg7vK3R5fHNGPo5",
      episodeNumber: 73,
      title: "Daily Chafetz Chaim - Day 73",
      description: "On Day 73, Rabbi Klapper examines the relationship between inner peace and external speech. Learn how cultivating menuchat hanefesh (peace of soul) natur...",
      releaseDate: "2025-04-18",
      durationMinutes: 2.35,
      spotifyUrl: "https://open.spotify.com/episode/2ntt8stJg7vK3R5fHNGPo5",
      embedUrl: "https://open.spotify.com/embed/episode/2ntt8stJg7vK3R5fHNGPo5",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5qxx1wwKhAmv6YghJOzm18",
      episodeNumber: 74,
      title: "Daily Chafetz Chaim - Day 74",
      description: "Day 74 focuses on the power of listening as a component of proper speech. Rabbi Klapper reveals how developing better listening skills enhances all aspec...",
      releaseDate: "2025-04-17",
      durationMinutes: 2.51,
      spotifyUrl: "https://open.spotify.com/episode/5qxx1wwKhAmv6YghJOzm18",
      embedUrl: "https://open.spotify.com/embed/episode/5qxx1wwKhAmv6YghJOzm18",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1rAA5AALiBwn7ZlJJ8WGnr",
      episodeNumber: 75,
      title: "Daily Chafetz Chaim - Day 75",
      description: "In Day 75, Rabbi Klapper explores the concept of spiritual protection through proper speech. Discover how shemiras halashon serves as a shield against s...",
      releaseDate: "2025-04-16",
      durationMinutes: 2.43,
      spotifyUrl: "https://open.spotify.com/episode/1rAA5AALiBwn7ZlJJ8WGnr",
      embedUrl: "https://open.spotify.com/embed/episode/1rAA5AALiBwn7ZlJJ8WGnr",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4uEE8EEMj4z36eKxRhKJvF",
      episodeNumber: 76,
      title: "Daily Chafetz Chaim - Day 76",
      description: "Day 76 delves into the role of preparation in improving our speech. Rabbi Klapper provides practical strategies for thinking before we speak and prepari...",
      releaseDate: "2025-04-15",
      durationMinutes: 2.46,
      spotifyUrl: "https://open.spotify.com/episode/4uEE8EEMj4z36eKxRhKJvF",
      embedUrl: "https://open.spotify.com/embed/episode/4uEE8EEMj4z36eKxRhKJvF",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3tII1IINkA5S8NXyQpJwSH",
      episodeNumber: 77,
      title: "Daily Chafetz Chaim - Day 77",
      description: "On Day 77, Rabbi Klapper examines the connection between Torah study and proper speech. Learn how immersing ourselves in Torah wisdom naturally refines...",
      releaseDate: "2025-04-14",
      durationMinutes: 2.39,
      spotifyUrl: "https://open.spotify.com/episode/3tII1IINkA5S8NXyQpJwSH",
      embedUrl: "https://open.spotify.com/embed/episode/3tII1IINkA5S8NXyQpJwSH",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6wMM4MMOl7v8bPbzSaOZNn",
      episodeNumber: 78,
      title: "Daily Chafetz Chaim - Day 78",
      description: "Day 78 focuses on the concept of balance in communication. Rabbi Klapper teaches how to find the middle path between excessive speech and inappropriate...",
      releaseDate: "2025-04-13",
      durationMinutes: 2.52,
      spotifyUrl: "https://open.spotify.com/episode/6wMM4MMOl7v8bPbzSaOZNn",
      embedUrl: "https://open.spotify.com/embed/episode/6wMM4MMOl7v8bPbzSaOZNn",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2xQQ7QQPlAT9cQd3Tp6aSR",
      episodeNumber: 79,
      title: "Daily Chafetz Chaim - Day 79",
      description: "In Day 79, Rabbi Klapper explores the transformative power of consistent practice. Discover how 79 days of focused attention to proper speech has create...",
      releaseDate: "2025-04-12",
      durationMinutes: 2.34,
      spotifyUrl: "https://open.spotify.com/episode/2xQQ7QQPlAT9cQd3Tp6aSR",
      embedUrl: "https://open.spotify.com/embed/episode/2xQQ7QQPlAT9cQd3Tp6aSR",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5aUU0UURofDHqW6HmHM6UV",
      episodeNumber: 80,
      title: "Daily Chafetz Chaim - Day 80",
      description: "Day 80 marks another significant milestone in our journey. Rabbi Klapper reflects on the cumulative impact of 80 days of dedicated work on speech refine...",
      releaseDate: "2025-04-11",
      durationMinutes: 2.48,
      spotifyUrl: "https://open.spotify.com/episode/5aUU0UURofDHqW6HmHM6UV",
      embedUrl: "https://open.spotify.com/embed/episode/5aUU0UURofDHqW6HmHM6UV",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1bYY4YYSr3h9vYF4RxQj1z",
      episodeNumber: 81,
      title: "Daily Chafetz Chaim - Day 81",
      description: "On Day 81, Rabbi Klapper examines the role of courage in maintaining proper speech standards. Learn how developing inner strength helps us resist social...",
      releaseDate: "2025-04-10",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/1bYY4YYSr3h9vYF4RxQj1z",
      embedUrl: "https://open.spotify.com/embed/episode/1bYY4YYSr3h9vYF4RxQj1z",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4ecc7ccVu5yKzT2TgUL8D3",
      episodeNumber: 82,
      title: "Daily Chafetz Chaim - Day 82",
      description: "Day 82 delves into the concept of spiritual sensitivity and how it affects our speech choices. Rabbi Klapper teaches how developing finer spiritual percep...",
      releaseDate: "2025-04-09",
      durationMinutes: 2.55,
      spotifyUrl: "https://open.spotify.com/episode/4ecc7ccVu5yKzT2TgUL8D3",
      embedUrl: "https://open.spotify.com/embed/episode/4ecc7ccVu5yKzT2TgUL8D3",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3dff0ffWxA3t6VhGHhTnG7",
      episodeNumber: 83,
      title: "Daily Chafetz Chaim - Day 83",
      description: "In Day 83, Rabbi Klapper explores the connection between wisdom and knowing when to remain silent. Discover the profound power of strategic silence in co...",
      releaseDate: "2025-04-08",
      durationMinutes: 2.37,
      spotifyUrl: "https://open.spotify.com/episode/3dff0ffWxA3t6VhGHhTnG7",
      embedUrl: "https://open.spotify.com/embed/episode/3dff0ffWxA3t6VhGHhTnG7",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6gii9iiXzEt23YJhEBKJ1A",
      episodeNumber: 84,
      title: "Daily Chafetz Chaim - Day 84",
      description: "Day 84 focuses on the relationship between self-respect and respectful speech toward others. Rabbi Klapper reveals how proper self-regard naturally lead...",
      releaseDate: "2025-04-07",
      durationMinutes: 2.49,
      spotifyUrl: "https://open.spotify.com/episode/6gii9iiXzEt23YJhEBKJ1A",
      embedUrl: "https://open.spotify.com/embed/episode/6gii9iiXzEt23YJhEBKJ1A",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2hmm2mmYaG3O5Z2sNfaLeE",
      episodeNumber: 85,
      title: "Daily Chafetz Chaim - Day 85",
      description: "On Day 85, Rabbi Klapper examines the concept of spiritual accountability and how our speech affects our standing before Heaven. Learn about the cosmic i...",
      releaseDate: "2025-04-06",
      durationMinutes: 2.44,
      spotifyUrl: "https://open.spotify.com/episode/2hmm2mmYaG3O5Z2sNfaLeE",
      embedUrl: "https://open.spotify.com/embed/episode/2hmm2mmYaG3O5Z2sNfaLeE",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5kpp8ppZbK6R8e1VQbfHmI",
      episodeNumber: 86,
      title: "Daily Chafetz Chaim - Day 86",
      description: "Day 86 delves into the power of positive speech patterns to reshape our inner world. Rabbi Klapper teaches how changing our external communication natur...",
      releaseDate: "2025-04-05",
      durationMinutes: 2.51,
      spotifyUrl: "https://open.spotify.com/episode/5kpp8ppZbK6R8e1VQbfHmI",
      embedUrl: "https://open.spotify.com/embed/episode/5kpp8ppZbK6R8e1VQbfHmI",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1lqq4qqcM9vR9f2hK8nKnM",
      episodeNumber: 87,
      title: "Daily Chafetz Chaim - Day 87",
      description: "In Day 87, Rabbi Klapper explores the concept of legacy and how our speech patterns influence future generations. Discover the long-term impact of our c...",
      releaseDate: "2025-04-04",
      durationMinutes: 2.38,
      spotifyUrl: "https://open.spotify.com/episode/1lqq4qqcM9vR9f2hK8nKnM",
      embedUrl: "https://open.spotify.com/embed/episode/1lqq4qqcM9vR9f2hK8nKnM",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4orr7rrdO2yWmqLgLVsOoQ",
      episodeNumber: 88,
      title: "Daily Chafetz Chaim - Day 88",
      description: "Day 88 focuses on the relationship between spiritual maturity and communication skills. Rabbi Klapper reveals how growing in wisdom naturally improves o...",
      releaseDate: "2025-04-03",
      durationMinutes: 2.46,
      spotifyUrl: "https://open.spotify.com/episode/4orr7rrdO2yWmqLgLVsOoQ",
      embedUrl: "https://open.spotify.com/embed/episode/4orr7rrdO2yWmqLgLVsOoQ",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3nss6sseP5zXppKmN8zPpU",
      episodeNumber: 89,
      title: "Daily Chafetz Chaim - Day 89",
      description: "On Day 89, Rabbi Klapper examines the power of words to create reality and how our speech literally shapes the world around us. Learn about the mystical...",
      releaseDate: "2025-04-02",
      durationMinutes: 2.53,
      spotifyUrl: "https://open.spotify.com/episode/3nss6sseP5zXppKmN8zPpU",
      embedUrl: "https://open.spotify.com/embed/episode/3nss6sseP5zXppKmN8zPpU",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6qww9wwfS6aT0rYgRFqKlX",
      episodeNumber: 90,
      title: "Daily Chafetz Chaim - Day 90",
      description: "Day 90 represents three full months of dedicated work on speech refinement. Rabbi Klapper reflects on the transformation that occurs through consistent p...",
      releaseDate: "2025-04-01",
      durationMinutes: 2.42,
      spotifyUrl: "https://open.spotify.com/episode/6qww9wwfS6aT0rYgRFqKlX",
      embedUrl: "https://open.spotify.com/embed/episode/6qww9wwfS6aT0rYgRFqKlX",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2rAA2AAgT9eU1tMqKSjRmZ",
      episodeNumber: 91,
      title: "Daily Chafetz Chaim - Day 91",
      description: "In Day 91, Rabbi Klapper explores the concept of spiritual elevation through refined speech. Discover how our communication choices either elevate or lo...",
      releaseDate: "2025-03-31",
      durationMinutes: 2.49,
      spotifyUrl: "https://open.spotify.com/episode/2rAA2AAgT9eU1tMqKSjRmZ",
      embedUrl: "https://open.spotify.com/embed/episode/2rAA2AAgT9eU1tMqKSjRmZ",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5uBB5BBhU2gzU6QbM6dGpC",
      episodeNumber: 92,
      title: "Daily Chafetz Chaim - Day 92",
      description: "Day 92 delves into the role of divine assistance in our efforts to improve our speech. Rabbi Klapper teaches how to invite Heavenly help in our work tow...",
      releaseDate: "2025-03-30",
      durationMinutes: 2.36,
      spotifyUrl: "https://open.spotify.com/episode/5uBB5BBhU2gzU6QbM6dGpC",
      embedUrl: "https://open.spotify.com/embed/episode/5uBB5BBhU2gzU6QbM6dGpC",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1vCC8CCiX5xF1AYMv9MJqF",
      episodeNumber: 93,
      title: "Daily Chafetz Chaim - Day 93",
      description: "On Day 93, Rabbi Klapper examines the connection between inner joy and positive speech patterns. Learn how cultivating simcha (joy) naturally leads to m...",
      releaseDate: "2025-03-29",
      durationMinutes: 2.47,
      spotifyUrl: "https://open.spotify.com/episode/1vCC8CCiX5xF1AYMv9MJqF",
      embedUrl: "https://open.spotify.com/embed/episode/1vCC8CCiX5xF1AYMv9MJqF",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4yFF1FFjY6y4YY3YNyBZsJ",
      episodeNumber: 94,
      title: "Daily Chafetz Chaim - Day 94",
      description: "Day 94 focuses on the concept of completion and how our speech reflects our inner state of wholeness. Rabbi Klapper explores the relationship between sp...",
      releaseDate: "2025-03-28",
      durationMinutes: 2.54,
      spotifyUrl: "https://open.spotify.com/episode/4yFF1FFjY6y4YY3YNyBZsJ",
      embedUrl: "https://open.spotify.com/embed/episode/4yFF1FFjY6y4YY3YNyBZsJ",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3xGG4GGkZA9l82XHjnDNvN",
      episodeNumber: 95,
      title: "Daily Chafetz Chaim - Day 95",
      description: "In Day 95, Rabbi Klapper explores the power of words to heal old wounds and create new possibilities. Discover how our speech can become a source of hea...",
      releaseDate: "2025-03-27",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/3xGG4GGkZA9l82XHjnDNvN",
      embedUrl: "https://open.spotify.com/embed/episode/3xGG4GGkZA9l82XHjnDNvN",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6aKK7KKlaD63BpMqM5FRwR",
      episodeNumber: 96,
      title: "Daily Chafetz Chaim - Day 96",
      description: "Day 96 delves into the concept of spiritual protection that comes from proper speech. Rabbi Klapper reveals how shemiras halashon creates a shield aroun...",
      releaseDate: "2025-03-26",
      durationMinutes: 2.48,
      spotifyUrl: "https://open.spotify.com/episode/6aKK7KKlaD63BpMqM5FRwR",
      embedUrl: "https://open.spotify.com/embed/episode/6aKK7KKlaD63BpMqM5FRwR",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2bLL0LLmbGe33CnFK2LSuU",
      episodeNumber: 97,
      title: "Daily Chafetz Chaim - Day 97",
      description: "On Day 97, Rabbi Klapper examines the role of preparation as we near the completion of our 125-day journey. Learn how to integrate these teachings into...",
      releaseDate: "2025-03-25",
      durationMinutes: 2.35,
      spotifyUrl: "https://open.spotify.com/episode/2bLL0LLmbGe33CnFK2LSuU",
      embedUrl: "https://open.spotify.com/embed/episode/2bLL0LLmbGe33CnFK2LSuU",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5eOO8OOnfJh66GvRP8oWxY",
      episodeNumber: 98,
      title: "Daily Chafetz Chaim - Day 98",
      description: "Day 98 focuses on the concept of mastery and how consistent practice has transformed our speech patterns. Rabbi Klapper reflects on the journey of growt...",
      releaseDate: "2025-03-24",
      durationMinutes: 2.52,
      spotifyUrl: "https://open.spotify.com/episode/5eOO8OOnfJh66GvRP8oWxY",
      embedUrl: "https://open.spotify.com/embed/episode/5eOO8OOnfJh66GvRP8oWxY",
    },
    {
      id: "4fPP1PPphKi99JwLSGBl1T",
      episodeNumber: 99,
      title: "Daily Chafetz Chaim - Day 99",
      description: "In Day 99, Rabbi Klapper explores the concept of spiritual refinement as we approach the completion of our journey. Discover how nearly 100 days of focu...",
      releaseDate: "2025-03-23",
      durationMinutes: 2.39,
      spotifyUrl: "https://open.spotify.com/episode/4fPP1PPphKi99JwLSGBl1T",
      embedUrl: "https://open.spotify.com/embed/episode/4fPP1PPphKi99JwLSGBl1T",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1gQQ4QQqiLj11KxMTHCm4U",
      episodeNumber: 100,
      title: "Daily Chafetz Chaim - Day 100",
      description: "Day 100! A major milestone in our journey through the Chafetz Chaim. Rabbi Klapper celebrates this achievement and reflects on the profound changes tha...",
      releaseDate: "2025-03-22",
      durationMinutes: 2.56,
      spotifyUrl: "https://open.spotify.com/episode/1gQQ4QQqiLj11KxMTHCm4U",
      embedUrl: "https://open.spotify.com/embed/episode/1gQQ4QQqiLj11KxMTHCm4U",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4hRR7RRrjMk44LyNUIDn7V",
      episodeNumber: 101,
      title: "Daily Chafetz Chaim - Day 101",
      description: "On Day 101, Rabbi Klapper explores the concept of renewal and how we can continue growing even after reaching significant milestones. Learn how to maint...",
      releaseDate: "2025-03-21",
      durationMinutes: 2.43,
      spotifyUrl: "https://open.spotify.com/episode/4hRR7RRrjMk44LyNUIDn7V",
      embedUrl: "https://open.spotify.com/embed/episode/4hRR7RRrjMk44LyNUIDn7V",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3iSS0SSkN4m33MzOV7q28W",
      episodeNumber: 102,
      title: "Daily Chafetz Chaim - Day 102",
      description: "Day 102 delves into the concept of spiritual momentum and how consistent practice creates powerful forward movement in our growth. Rabbi Klapper provides...",
      releaseDate: "2025-03-20",
      durationMinutes: 2.47,
      spotifyUrl: "https://open.spotify.com/episode/3iSS0SSkN4m33MzOV7q28W",
      embedUrl: "https://open.spotify.com/embed/episode/3iSS0SSkN4m33MzOV7q28W",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6jTT3TTlO7p66P0RYLtU9X",
      episodeNumber: 103,
      title: "Daily Chafetz Chaim - Day 103",
      description: "In Day 103, Rabbi Klapper examines the power of words to create lasting impact. Discover how our speech can leave positive imprints that continue to in...",
      releaseDate: "2025-03-19",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/6jTT3TTlO7p66P0RYLtU9X",
      embedUrl: "https://open.spotify.com/embed/episode/6jTT3TTlO7p66P0RYLtU9X",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2kUU6UUmP8r99RSzBdYu0Y",
      episodeNumber: 104,
      title: "Daily Chafetz Chaim - Day 104",
      description: "Day 104 focuses on the concept of spiritual inheritance and how our refined speech patterns become gifts we pass on to future generations. Rabbi Klappe...",
      releaseDate: "2025-03-18",
      durationMinutes: 2.54,
      spotifyUrl: "https://open.spotify.com/episode/2kUU6UUmP8r99RSzBdYu0Y",
      embedUrl: "https://open.spotify.com/embed/episode/2kUU6UUmP8r99RSzBdYu0Y",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5lVV9VVnQ3v00VtQBM9w3Z",
      episodeNumber: 105,
      title: "Daily Chafetz Chaim - Day 105",
      description: "On Day 105, Rabbi Klapper explores the relationship between humility and mastery. Learn how true expertise in shemiras halashon leads to greater modesty...",
      releaseDate: "2025-03-17",
      durationMinutes: 2.38,
      spotifyUrl: "https://open.spotify.com/episode/5lVV9VVnQ3v00VtQBM9w3Z",
      embedUrl: "https://open.spotify.com/embed/episode/5lVV9VVnQ3v00VtQBM9w3Z",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1mWW2WWoR6w33WuREfJxl4",
      episodeNumber: 106,
      title: "Daily Chafetz Chaim - Day 106",
      description: "Day 106 delves into the concept of spiritual leadership through example. Rabbi Klapper teaches how our refined speech naturally inspires others to impr...",
      releaseDate: "2025-03-16",
      durationMinutes: 2.49,
      spotifyUrl: "https://open.spotify.com/episode/1mWW2WWoR6w33WuREfJxl4",
      embedUrl: "https://open.spotify.com/embed/episode/1mWW2WWoR6w33WuREfJxl4",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4nXX5XXpS9z66ZvSGBGym7",
      episodeNumber: 107,
      title: "Daily Chafetz Chaim - Day 107",
      description: "In Day 107, Rabbi Klapper explores the power of intention in our final weeks of study. Discover how to approach the completion of this journey with the...",
      releaseDate: "2025-03-15",
      durationMinutes: 2.44,
      spotifyUrl: "https://open.spotify.com/episode/4nXX5XXpS9z66ZvSGBGym7",
      embedUrl: "https://open.spotify.com/embed/episode/4nXX5XXpS9z66ZvSGBGym7",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3oYY8YYqTBz99cxwHHMo38",
      episodeNumber: 108,
      title: "Daily Chafetz Chaim - Day 108",
      description: "Day 108 focuses on the concept of integration - how to weave the lessons of shemiras halashon into every aspect of our lives. Rabbi Klapper provides pr...",
      releaseDate: "2025-03-14",
      durationMinutes: 2.51,
      spotifyUrl: "https://open.spotify.com/episode/3oYY8YYqTBz99cxwHHMo38",
      embedUrl: "https://open.spotify.com/embed/episode/3oYY8YYqTBz99cxwHHMo38",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6pZZ1ZZrUE222ewUIrXqj9",
      episodeNumber: 109,
      title: "Daily Chafetz Chaim - Day 109",
      description: "On Day 109, Rabbi Klapper examines the concept of spiritual consciousness and how our awareness has been elevated through consistent practice. Learn how t...",
      releaseDate: "2025-03-13",
      durationMinutes: 2.37,
      spotifyUrl: "https://open.spotify.com/episode/6pZZ1ZZrUE222ewUIrXqj9",
      embedUrl: "https://open.spotify.com/embed/episode/6pZZ1ZZrUE222ewUIrXqj9",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2qaa4aasVH555fxVJ6pKkA",
      episodeNumber: 110,
      title: "Daily Chafetz Chaim - Day 110",
      description: "Day 110 delves into the relationship between gratitude and proper speech. Rabbi Klapper reveals how our journey through the Chafetz Chaim has cultivate...",
      releaseDate: "2025-03-12",
      durationMinutes: 2.48,
      spotifyUrl: "https://open.spotify.com/episode/2qaa4aasVH555fxVJ6pKkA",
      embedUrl: "https://open.spotify.com/embed/episode/2qaa4aasVH555fxVJ6pKkA",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5rbb7bbvWK888gyWKKMglB",
      episodeNumber: 111,
      title: "Daily Chafetz Chaim - Day 111",
      description: "In Day 111, Rabbi Klapper explores the concept of spiritual acceleration as we approach the completion of our study. Discover how the final weeks can pr...",
      releaseDate: "2025-03-11",
      durationMinutes: 2.42,
      spotifyUrl: "https://open.spotify.com/episode/5rbb7bbvWK888gyWKKMglB",
      embedUrl: "https://open.spotify.com/embed/episode/5rbb7bbvWK888gyWKKMglB",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1scc0ccwXN111hzXL8qhmE",
      episodeNumber: 112,
      title: "Daily Chafetz Chaim - Day 112",
      description: "Day 112 focuses on the power of reflection and how looking back on our journey reveals the profound transformation that has occurred. Rabbi Klapper guid...",
      releaseDate: "2025-03-10",
      durationMinutes: 2.55,
      spotifyUrl: "https://open.spotify.com/episode/1scc0ccwXN111hzXL8qhmE",
      embedUrl: "https://open.spotify.com/embed/episode/1scc0ccwXN111hzXL8qhmE",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4tdd3ddxYQ444k0YN3jKnG",
      episodeNumber: 113,
      title: "Daily Chafetz Chaim - Day 113",
      description: "On Day 113, Rabbi Klapper examines the concept of spiritual completion and how true mastery is a beginning, not an end. Learn how to view the conclusio...",
      releaseDate: "2025-03-09",
      durationMinutes: 2.39,
      spotifyUrl: "https://open.spotify.com/episode/4tdd3ddxYQ444k0YN3jKnG",
      embedUrl: "https://open.spotify.com/embed/episode/4tdd3ddxYQ444k0YN3jKnG",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3uee6eeyZT777m1ZO8LJnJ",
      episodeNumber: 114,
      title: "Daily Chafetz Chaim - Day 114",
      description: "Day 114 delves into the concept of spiritual legacy and how our refined speech patterns will continue to impact the world long after our study is compl...",
      releaseDate: "2025-03-08",
      durationMinutes: 2.46,
      spotifyUrl: "https://open.spotify.com/episode/3uee6eeyZT777m1ZO8LJnJ",
      embedUrl: "https://open.spotify.com/embed/episode/3uee6eeyZT777m1ZO8LJnJ",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6vff9ffzaU000n2aP9MKpK",
      episodeNumber: 115,
      title: "Daily Chafetz Chaim - Day 115",
      description: "In Day 115, Rabbi Klapper explores the power of commitment and how our dedication to this daily practice has transformed our relationship with speech it...",
      releaseDate: "2025-03-07",
      durationMinutes: 2.53,
      spotifyUrl: "https://open.spotify.com/episode/6vff9ffzaU000n2aP9MKpK",
      embedUrl: "https://open.spotify.com/embed/episode/6vff9ffzaU000n2aP9MKpK",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2wgg2ggAaX333o3bRJXLrL",
      episodeNumber: 116,
      title: "Daily Chafetz Chaim - Day 116",
      description: "Day 116 focuses on the concept of spiritual preparation for completion. Rabbi Klapper guides us in preparing our hearts and minds for the conclusion of...",
      releaseDate: "2025-03-06",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/2wgg2ggAaX333o3bRJXLrL",
      embedUrl: "https://open.spotify.com/embed/episode/2wgg2ggAaX333o3bRJXLrL",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5xhh5hhBbY666p4cS8KMsM",
      episodeNumber: 117,
      title: "Daily Chafetz Chaim - Day 117",
      description: "On Day 117, Rabbi Klapper examines the relationship between wisdom and humility as we near the end of our formal study. Discover how true knowledge lead...",
      releaseDate: "2025-03-05",
      durationMinutes: 2.48,
      spotifyUrl: "https://open.spotify.com/episode/5xhh5hhBbY666p4cS8KMsM",
      embedUrl: "https://open.spotify.com/embed/episode/5xhh5hhBbY666p4cS8KMsM",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1yii8iicZ999q5dT9gB0nN",
      episodeNumber: 118,
      title: "Daily Chafetz Chaim - Day 118",
      description: "Day 118 delves into the concept of continuous growth and how the principles we've learned will continue to unfold throughout our lives. Rabbi Klapper te...",
      releaseDate: "2025-03-04",
      durationMinutes: 2.36,
      spotifyUrl: "https://open.spotify.com/episode/1yii8iicZ999q5dT9gB0nN",
      embedUrl: "https://open.spotify.com/embed/episode/1yii8iicZ999q5dT9gB0nN",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "4zjj1jjdac22r6eUAjJPoO",
      episodeNumber: 119,
      title: "Daily Chafetz Chaim - Day 119",
      description: "In Day 119, Rabbi Klapper explores the power of intention as we approach the final days of our journey. Learn how to carry the spirit of this practice f...",
      releaseDate: "2025-03-03",
      durationMinutes: 2.52,
      spotifyUrl: "https://open.spotify.com/episode/4zjj1jjdac22r6eUAjJPoO",
      embedUrl: "https://open.spotify.com/embed/episode/4zjj1jjdac22r6eUAjJPoO",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3akk4kkebd55s7fVBkKQpP",
      episodeNumber: 120,
      title: "Daily Chafetz Chaim - Day 120",
      description: "Day 120 marks the final countdown to completion. Rabbi Klapper reflects on the incredible journey we've shared and the transformation that has occurred t...",
      releaseDate: "2025-03-02",
      durationMinutes: 2.44,
      spotifyUrl: "https://open.spotify.com/episode/3akk4kkebd55s7fVBkKQpP",
      embedUrl: "https://open.spotify.com/embed/episode/3akk4kkebd55s7fVBkKQpP",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "6bll7llffe88t8gWE9d3qQ",
      episodeNumber: 121,
      title: "Daily Chafetz Chaim - Day 121",
      description: "On Day 121, Rabbi Klapper explores the concept of gratitude for the journey and the privilege of studying these holy teachings. Discover how appreciatio...",
      releaseDate: "2025-03-01",
      durationMinutes: 2.49,
      spotifyUrl: "https://open.spotify.com/episode/6bll7llffe88t8gWE9d3qQ",
      embedUrl: "https://open.spotify.com/embed/episode/6bll7llffe88t8gWE9d3qQ",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "2cmm0mmggf11u9hXF0f4rR",
      episodeNumber: 122,
      title: "Daily Chafetz Chaim - Day 122",
      description: "Day 122 delves into the concept of spiritual momentum and how to maintain the growth we've achieved through this intensive period of study. Rabbi Klappe...",
      releaseDate: "2025-02-28",
      durationMinutes: 2.41,
      spotifyUrl: "https://open.spotify.com/episode/2cmm0mmggf11u9hXF0f4rR",
      embedUrl: "https://open.spotify.com/embed/episode/2cmm0mmggf11u9hXF0f4rR",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "5dnn3nnhhi44v0kYG3G5sS",
      episodeNumber: 123,
      title: "Daily Chafetz Chaim - Day 123",
      description: "In Day 123, Rabbi Klapper examines the concept of completion with humility. As we near the end of our formal study, learn how to approach this achievem...",
      releaseDate: "2025-02-27",
      durationMinutes: 2.56,
      spotifyUrl: "https://open.spotify.com/episode/5dnn3nnhhi44v0kYG3G5sS",
      embedUrl: "https://open.spotify.com/embed/episode/5dnn3nnhhi44v0kYG3G5sS",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "1eoo6oojj77w1lZH6HK6tT",
      episodeNumber: 124,
      title: "Daily Chafetz Chaim - Day 124",
      description: "Day 124 - the penultimate day of our journey. Rabbi Klapper prepares us for tomorrow's conclusion while celebrating the incredible transformation that ha...",
      releaseDate: "2025-02-26",
      durationMinutes: 2.38,
      spotifyUrl: "https://open.spotify.com/episode/1eoo6oojj77w1lZH6HK6tT",
      embedUrl: "https://open.spotify.com/embed/episode/1eoo6oojj77w1lZH6HK6tT",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    },
    {
      id: "3KAGA4sfYzdyrNfh67imwD",
      episodeNumber: 125,
      title: "Daily Chafetz Chaim - Day 125",
      description: "Day 125 - the final day of our transformative journey through the Chafetz Chaim. Rabbi Klapper brings our study to a meaningful conclusion, celebrating our growth and providing guidance for continuing this sacred work in our daily lives. This is not an ending, but a graduation into a lifetime of mindful, holy speech.",
      releaseDate: "2024-06-07",
      durationMinutes: 2.21,
      spotifyUrl: "https://open.spotify.com/episode/3KAGA4sfYzdyrNfh67imwD",
      embedUrl: "https://open.spotify.com/embed/episode/3KAGA4sfYzdyrNfh67imwD",
      imageUrl: "https://i.scdn.co/image/ab6765630000ba8ac868f85b0d4c429c32679e92"
    }
  ]
};

// Make data available globally
window.shemiras_halashon_daily_data = shemiras_halashon_daily_data;